/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "common": {
        "PageNotFound": string;
        "HELLO": string;
        "PRODUCT": {
            "NEW": string;
        };
        "ENGLISH": string;
        "ARRAY": [
            string,
            string,
            string
        ];
        "ONLY_EN_KEY": string;
        "cat_name": string;
        "set-up-password": {
            "heading": string;
            "title": string;
            "followLink": string;
        };
        "dot.test": string;
        "day_interval": {
            "one": string;
            "other": string;
            "zero": string;
        };
        "nested": string;
        "nested-no-args": string;
        "nest1": {
            "nest2": {
                "nest3": string;
            };
        };
        "CURRENT_LANGUAGE": string;
    };
    "validation": {
        "email": string;
        "password": string;
        "IS_STRING": string;
        "IS_BOOLEAN": string;
        "NOT_EMPTY": string;
        "INVALID_BOOLEAN": string;
        "INVALID_EMAIL": string;
        "MIN": string;
        "MAX": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
