name: m88-portal

services:
# ===============================
# Postgres
  m88_postgres:
    container_name: m88_postgres
    restart: unless-stopped
    image: postgres:17-alpine
    env_file: ./.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    ports:
      - 5677:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - m88_portal

  m88_pgAdmin:
    container_name: m88_pgAdmin
    restart: unless-stopped
    image: dpage/pgadmin4:latest
    user: '0:0'
    env_file: ./.env
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    ports:
      - 5670:80
    networks:
      - m88_portal
    depends_on:
      - m88_postgres
# ===============================
# Redis
  m88_redis:
    container_name: m88_redis
    restart: unless-stopped
    image: redis:7-alpine
    env_file: ./.env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./data/redis:/data
    ports:
      - 5660:6379
    networks:
      - m88_portal
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10

  m88_redis_insight:
    container_name: m88_redis_insight
    restart: unless-stopped
    image: redis/redisinsight:latest
    env_file: ./.env
    volumes:
      - ./data/redisinsight:/data
    ports:
      - 5661:5540
    networks:
      - m88_portal
    depends_on:
      - m88_redis
# ===============================
# Networks
networks:
  m88_portal:
    name: m88_portal
    external: true