// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "HeaderNavs": {
    "home": {
      "label": "Home"
    },
    "about": {
      "label": "About"
    },
    "client": {
      "label": "Client"
    },
    "server": {
      "label": "Server"
    },
    "static": {
      "label": "Static"
    }
  },
  "Error": {
    "description": "<p>We've unfortunately encountered an error.</p><p>You can try to <retry>reload the page</retry> you were visiting.</p>",
    "title": "Something went wrong!"
  },
  "Header": {
    "logo": "M88 Portal",
    "login": "Log in",
    "toggleMenu": "Toggle Menu"
  },
  "HomePage": {
    "about": "Go to the about page",
    "title": "Hello world!"
  },
  "LocaleSwitcher": {
    "label": "Language",
    "locale": "{locale, select, en {Eng} ru {Рус} other {Unknown}}",
    "en": "Eng",
    "ru": "Рус"
  },
  "Manifest": {
    "description": "M88 Portal test project",
    "name": "M88 Portal",
    "shortName": "M88"
  },
  "NotFoundPage": {
    "description": "Please double-check the browser address bar or use the navigation to go to a known page.",
    "title": "Page not found"
  },
  "Page": {
    "home": "Home"
  },
  "LocaleLayout": {
    "title": "LocaleLayout"
  },
  "ThemeToggle": {
    "dark": "Dark",
    "light": "Light",
    "system": "System",
    "toggleTheme": "Toggle theme"
  },
  "Footer": {
    "copyright": "M88 Portal. All rights reserved."
  }
};
export default messages;